module.exports = {
  dev: {
    "default-src": ["'self'", "*", "data:", "https:"],
    "font-src": ["'self'", "https:"],
    "script-src": ["'unsafe-inline'"],
    "img-src": ["data:", "https:", "blob:", "'self'", "http://localhost:4000"],
    "media-src": [
      "data:",
      "https:",
      "blob:",
      "'self'",
      "http://localhost:4000",
    ],
    "style-src": ["'unsafe-inline'"],
    "connect-src": ["https://api.coingecko.com"],
    "script-src-elem": ["'unsafe-inline'", "*"],
    "style-src-elem": ["'unsafe-inline'", "https:"],
  },
  prod: {
    "default-src": ["'self'", "*", "data:", "https:"],
    "font-src": ["'self'", "https:"],
    "script-src": ["'unsafe-inline'"],
    "img-src": ["data:", "https:", "blob:", "'self'"],
    "media-src": ["data:", "https:", "blob:", "'self'"],
    "style-src": ["'unsafe-inline'"],
    "connect-src": ["https://api.coingecko.com"],
    "script-src-elem": ["'unsafe-inline'", "*"],
    "style-src-elem": ["'unsafe-inline'", "https:"],
  },
};
