/* eslint-disable quotes */
/* eslint-disable no-template-curly-in-string */

const cssLines = [
  ".widget-container {",
  "  position: absolute;",
  "  bottom: 3rem;",
  "  right: 2rem;",
  "  width: 20rem;",
  "",
  "  animation-duration: 1s;",
  "  animation-name: slideIn;",
  "",
  "  background-color: #ffffffc4;",
  "  padding: 1rem;",
  "  border-radius: 9px;",
  "}",
  "",
  "@keyframes slideIn {",
  "  from {",
  "    right: -20rem;",
  "  }",
  "  to {",
  "    right: 2rem;",
  "  }",
  "}",
  "",
  ".slide-out {",
  "  animation-duration: 1s !important;",
  "  animation-name: slideOut !important;",
  "}",
  "",
  "@keyframes slideOut {",
  "  from {",
  "    right: 2rem;",
  "  }",
  "  ",
  "  ",
  "  to {",
  "    right: -20rem;",
  "  }",
  "}",
  "",
  ".logo {",
  "  width: 100%;",
  "",
  "  animation: rotateLogo 4s infinite linear;",
  "}",
  "",
  "@keyframes rotateLogo {",
  "  0% {",
  "    transform: rotateY(0deg);",
  "  }",
  "  50% {",
  "    transform: rotateY(90deg);",
  "  }",
  "  100% {",
  "    transform: rotateY(0deg);",
  "  }",
  "}",
  "",
  "h3 {",
  '  font-family: "Noto Sans JP", sans-serif;',
  "  font-weight: 500;",
  "  text-align: center;",
  "}",
  "",
  ".p-container {",
  "  width: 100%;",
  "  overflow: hidden;",
  "}",
  ".p-container > p {",
  "  margin: 0;",
  "  width: max-content;",
  "",
  '  font-family: "Noto Sans JP", sans-serif;',
  "  font-weight: 400;",
  "",
  "  animation: translateText 10s 2s infinite linear;",
  "}",
  "",
  "@keyframes translateText {",
  "  from {",
  "    transform: translateX(0);",
  "  }",
  "  to {",
  "    transform: translateX(-100%);",
  "  }",
  "}",
];

export const cssSnippet = cssLines.join("\n");
