export const AVAILABLE_GOOGLE_FONTS = [
  "Roboto",
  "Open Sans",
  "Noto Sans JP",
  "Lato",
  "Montserrat",
  "Roboto Condensed",
  "Source Sans Pro",
  "Oswald",
  "Poppins",
  "Noto Sans",
  "Roboto Mono",
  "Raleway",
  "Ubuntu",
  "PT Sans",
  "Merriweather",
  "Roboto Slab",
  "Nunito",
  "Playfair Display",
  "Noto Sans KR",
  "Open Sans Condensed",
  "Rubik",
  "Lora",
  "Noto Sans TC",
  "Mukta",
  "Work Sans",
  "Hind Siliguri",
  "Nunito Sans",
  "Fira Sans",
  "Nanum Gothic",
  "PT Serif",
  "Inter",
  "Titillium Web",
  "Quicksand",
  "Noto Serif",
  "Karla",
  "Barlow",
  "Heebo",
  "Inconsolata",
  "Noto Sans SC",
  "Oxygen",
  "Libre Baskerville",
  "Teko",
  "PT Sans Narrow",
  "Arimo",
  "Libre Franklin",
  "Dosis",
  "Anton",
  "Josefin Sans",
  "Yanone Kaffeesatz",
  "Source Code Pro",
  "Bebas Neue",
  "Mulish",
  "Bitter",
  "IBM Plex Sans",
  "Cabin",
  "Noto Sans HK",
  "Hind",
  "Varela Round",
  "Dancing Script",
  "Crimson Text",
  "Prompt",
  "Lobster",
  "Fjalla One",
  "Abel",
  "Source Serif Pro",
  "Cairo",
  "Barlow Condensed",
  "Staatliches",
  "EB Garamond",
  "Arvo",
  "Padauk",
  "DM Sans",
  "Zilla Slab",
  "Comfortaa",
  "Indie Flower",
  "Pacifico",
  "Exo 2",
  "Kanit",
  "Shadows Into Light",
  "Merriweather Sans",
  "Asap",
  "Overpass",
  "Rajdhani",
  "Questrial",
  "Noto Serif JP",
  "Abril Fatface",
  "Yellowtail",
  "Hind Madurai",
  "Assistant",
  "Slabo 27px",
  "Tajawal",
  "Fira Sans Condensed",
  "Maven Pro",
  "Catamaran",
  "Cormorant Garamond",
  "Archivo Narrow",
  "Martel",
  "Exo",
  "IBM Plex Serif",
  "Caveat",
  "Amatic SC",
  "Domine",
  "Play",
  "Bree Serif",
  "Alfa Slab One",
  "Nanum Myeongjo",
  "Antic Slab",
  "Acme",
  "Vollkorn",
  "Manrope",
  "Righteous",
  "Signika",
  "Secular One",
  "Barlow Semi Condensed",
  "Archivo",
  "Crete Round",
  "M PLUS Rounded 1c",
  "Sarabun",
  "Cinzel",
  "Alegreya Sans",
  "Satisfy",
  "Permanent Marker",
  "Architects Daughter",
  "ABeeZee",
  "Tinos",
  "Patua One",
  "Amiri",
  "Ubuntu Condensed",
  "Almarai",
  "Fredoka One",
  "Patrick Hand",
  "Courgette",
  "Alegreya",
  "Spartan",
  "M PLUS 1p",
  "Gothic A1",
  "Kaushan Script",
  "Public Sans",
  "Lobster Two",
  "Jost",
  "Yantramanav",
  "Merienda",
  "Archivo Black",
  "PT Sans Caption",
  "Kalam",
  "Great Vibes",
  "Spectral",
  "Frank Ruhl Libre",
  "Chakra Petch",
  "Cardo",
  "Signika Negative",
  "Red Hat Display",
  "Balsamiq Sans",
  "Russo One",
  "Francois One",
  "Noto Serif TC",
  "IBM Plex Mono",
  "Prata",
  "Didact Gothic",
  "Encode Sans",
  "Noticia Text",
  "Orbitron",
  "Quattrocento Sans",
  "Sacramento",
  "Cuprum",
  "Hind Guntur",
  "Baloo 2",
  "Monda",
  "Parisienne",
  "Chivo",
  "Old Standard TT",
  "DM Serif Display",
  "Cantarell",
  "Concert One",
  "Pathway Gothic One",
  "Rokkitt",
  "Gloria Hallelujah",
  "Volkhov",
  "Saira Condensed",
  "Ropa Sans",
  "Asap Condensed",
  "Changa",
  "News Cycle",
  "Jomhuria",
  "Playfair Display SC",
  "Stint Ultra Condensed",
  "Noto Serif KR",
  "Special Elite",
  "Josefin Slab",
  "Noto Serif SC",
  "Passion One",
  "Cookie",
  "Sawarabi Mincho",
  "Sigmar One",
  "Unna",
  "Montserrat Alternates",
  "Ultra",
  "Quattrocento",
  "Poiret One",
  "Faustina",
  "Taviraj",
  "Advent Pro",
  "Cormorant",
  "Bai Jamjuree",
  "Press Start 2P",
  "Neuton",
  "Mitr",
  "Vidaloka",
  "Istok Web",
  "Hammersmith One",
  "Sanchez",
  "Electrolize",
  "Philosopher",
  "Monoton",
  "Gentium Book Basic",
  "Luckiest Guy",
  "Bangers",
  "Arapey",
  "Mate SC",
  "Fira Sans Extra Condensed",
  "Handlee",
  "Economica",
  "Rock Salt",
  "Ubuntu Mono",
  "Khand",
  "Saira",
  "Pragati Narrow",
  "Marcellus",
  "Karma",
  "Playball",
  "Hind Vadodara",
  "Tangerine",
  "PT Mono",
  "Space Mono",
  "Gudea",
  "Big Shoulders Display",
  "Neucha",
  "Alata",
  "Cabin Condensed",
  "BenchNine",
  "Ruda",
  "Gentium Basic",
  "Lusitana",
  "Fugaz One",
  "El Messiri",
  "Saira Semi Condensed",
  "Sawarabi Gothic",
  "Alef",
  "Alice",
  "Saira Extra Condensed",
  "Actor",
  "Unica One",
  "Amaranth",
  "Allura",
  "Jura",
  "Viga",
  "Homemade Apple",
  "Nanum Gothic Coding",
  "Bad Script",
  "Marck Script",
  "Yeseva One",
  "Adamina",
  "Julius Sans One",
  "Ramabhadra",
  "Antic",
  "Sarala",
  "Carter One",
  "Paytone One",
  "Khula",
  "Palanquin",
  "Nanum Pen Script",
  "Pontano Sans",
  "Tenor Sans",
  "Armata",
  "Aleo",
  "Aclonica",
  "DM Serif Text",
  "Abhaya Libre",
  "Mali",
  "Kosugi Maru",
  "Nothing You Could Do",
  "Syncopate",
  "Cutive Mono",
  "Sorts Mill Goudy",
  "Bungee",
  "Shadows Into Light Two",
  "Quantico",
  "Markazi Text",
  "Audiowide",
  "Pridi",
  "Knewave",
  "Gelasio",
  "Rufina",
  "Varela",
  "Jaldi",
  "Alex Brush",
  "Rubik Mono One",
  "Damion",
  "Oleo Script",
  "Mr Dafoe",
  "Cantata One",
  "Sen",
  "Squada One",
  "Arima Madurai",
  "Mandali",
  "Gruppo",
  "Gochi Hand",
  "Cousine",
  "Glegoo",
  "Black Ops One",
  "Black Han Sans",
  "Suez One",
  "Fira Mono",
  "Rancho",
  "Lilita One",
  "Average",
  "Mada",
  "Basic",
  "Lexend Deca",
  "Courier Prime",
  "Chewy",
  "Share Tech Mono",
  "Berkshire Swash",
  "Voltaire",
  "Sriracha",
  "Allerta",
  "Red Hat Text",
  "Niconne",
  "Michroma",
  "Mate",
  "Just Another Hand",
  "Yrsa",
  "Encode Sans Condensed",
  "Laila",
  "Spinnaker",
  "Pinyon Script",
  "Martel Sans",
  "Fredericka the Great",
  "Six Caps",
  "Reem Kufi",
  "Candal",
  "Arsenal",
  "Itim",
  "Coda",
  "Crimson Pro",
  "Sintony",
  "Alegreya Sans SC",
  "Days One",
  "Lalezar",
  "Kreon",
  "Coda Caption",
  "Forum",
  "Changa One",
  "Enriqueta",
  "Allan",
  "Literata",
  "Italianno",
  "Aldrich",
  "Shrikhand",
  "Reenie Beanie",
  "Lemonada",
  "Pangolin",
  "Caveat Brush",
  "VT323",
  "Eczar",
  "Mukta Vaani",
  "Overlock",
  "Covered By Your Grace",
  "Kameron",
  "PT Serif Caption",
  "Cabin Sketch",
  "Mukta Malar",
  "Bubblegum Sans",
  "Anonymous Pro",
  "Rye",
  "Capriola",
  "Bevan",
  "Judson",
  "Sansita",
  "Niramit",
  "Krub",
  "Boogaloo",
  "Nobile",
  "Telex",
  "Norican",
  "Lateef",
  "Annie Use Your Telescope",
  "Darker Grotesque",
  "Yesteryear",
  "Cinzel Decorative",
  "Bowlby One SC",
  "Rambla",
  "Pattaya",
  "Arbutus Slab",
  "Londrina Solid",
  "Jua",
  "Scheherazade",
  "Leckerli One",
  "Holtwood One SC",
  "Ovo",
  "Molengo",
  "Caudex",
  "Herr Von Muellerhoff",
  "Mountains of Christmas",
  "Arizonia",
  "Trirong",
  "Charm",
  "Mrs Saint Delafield",
  "Seaweed Script",
  "Amita",
  "Maitree",
  "Biryani",
  "Bungee Inline",
  "Racing Sans One",
  "Castoro",
  "Chonburi",
  "Libre Caslon Text",
  "Epilogue",
  "Alegreya SC",
  "Baloo Tamma 2",
  "Gilda Display",
  "Kristi",
  "Belgrano",
  "Nixie One",
  "Do Hyeon",
  "Corben",
  "Rochester",
  "Share",
  "Lustria",
  "Miriam Libre",
  "Average Sans",
  "Jockey One",
  "Allerta Stencil",
  "Overpass Mono",
  "Nanum Brush Script",
  "Coming Soon",
  "Scada",
  "Contrail One",
  "Delius",
  "Graduate",
  "Fauna One",
  "Oranienbaum",
  "Suranna",
  "Athiti",
  "Marcellus SC",
  "Rozha One",
  "Cedarville Cursive",
  "Krona One",
  "IBM Plex Sans Condensed",
  "Palanquin Dark",
  "Sunflower",
  "GFS Didot",
  "Baloo Tammudu 2",
  "Mr De Haviland",
  "Trocchi",
  "Carrois Gothic",
  "Coustard",
  "Magra",
  "Belleza",
  "K2D",
  "Halant",
  "Titan One",
  "Sora",
  "Copse",
  "Carme",
  "Averia Serif Libre",
  "Comic Neue",
  "Petit Formal Script",
  "Grand Hotel",
  "Be Vietnam",
  "Commissioner",
  "Marmelad",
  "Aladin",
  "Slabo 13px",
  "La Belle Aurore",
  "Rosario",
  "Amiko",
  "Cormorant Infant",
  "Calligraffitti",
  "Metrophobic",
  "Merienda One",
  "Love Ya Like A Sister",
  "Thasadith",
  "Kosugi",
  "Mallanna",
  "Manjari",
  "Baskervville",
  "Averia Libre",
  "Radley",
  "Mirza",
  "Baloo Da 2",
  "Encode Sans Semi Condensed",
  "Wallpoet",
  "Podkova",
  "Duru Sans",
  "IM Fell DW Pica",
  "Poly",
  "Cambay",
  "Oxygen Mono",
  "Schoolbell",
  "Spectral SC",
  "Buenard",
  "Grandstander",
  "Fira Code",
  "Esteban",
  "NTR",
  "IM Fell Double Pica",
  "Sniglet",
  "Marvel",
  "Goudy Bookletter 1911",
  "Kumbh Sans",
  "Bellefair",
  "Kelly Slab",
  "Alatsi",
  "Amethysta",
  "Cormorant SC",
  "Rammetto One",
  "Space Grotesk",
  "Bungee Shade",
  "Bentham",
  "ZCOOL XiaoWei",
  "Hanuman",
  "Megrim",
  "Lekton",
  "Alike",
  "Gabriela",
  "IM Fell English",
  "Monsieur La Doulaise",
  "Cambo",
  "Cutive",
  "Hepta Slab",
  "Andada",
  "Turret Road",
  "Bowlby One",
  "Gravitas One",
  "Harmattan",
  "Libre Barcode 39",
  "Waiting for the Sunrise",
  "Balthazar",
  "Convergence",
  "Kadwa",
  "Sofia",
  "Chelsea Market",
  "Blinker",
  "Limelight",
  "Hi Melody",
  "Gugi",
  "Emilys Candy",
  "Sue Ellen Francisco",
  "Creepster",
  "Rouge Script",
  "Lemon",
  "Fanwood Text",
  "David Libre",
  "UnifrakturMaguntia",
  "Dawning of a New Day",
  "Original Surfer",
  "Montez",
  "B612 Mono",
  "Finger Paint",
  "Zeyada",
  "Sedgwick Ave",
  "Grenze Gotisch",
  "Raleway Dots",
  "Sarpanch",
  "Pompiere",
  "Brawler",
  "Qwigley",
  "Battambang",
  "Proza Libre",
  "Oregano",
  "Doppio One",
  "Averia Sans Libre",
  "Baumans",
  "Anaheim",
  "Dokdo",
  "Frijole",
  "KoHo",
  "Rasa",
  "Skranji",
  "Inder",
  "Bodoni Moda",
  "JetBrains Mono",
  "Almendra",
  "Ceviche One",
  "Expletus Sans",
  "Kurale",
  "Oleo Script Swash Caps",
  "Quando",
  "Yatra One",
  "Give You Glory",
  "Vast Shadow",
  "Stardos Stencil",
  "Montaga",
  "Recursive",
  "Aguafina Script",
  "Patrick Hand SC",
  "Gurajada",
  "Meddon",
  "Freckle Face",
  "Antic Didone",
  "Wendy One",
  "Happy Monkey",
  "Shojumaru",
  "Della Respira",
  "Andika",
  "Alike Angular",
  "Federo",
  "DM Mono",
  "Over the Rainbow",
  "Numans",
  "Mansalva",
  "Homenaje",
  "BioRhyme",
  "Atma",
  "Rakkas",
  "Galada",
  "Oxanium",
  "Fondamento",
  "Clicker Script",
  "Aref Ruqaa",
  "Denk One",
  "Orienta",
  "Livvic",
  "Vesper Libre",
  "Sail",
  "Faster One",
  "Mouse Memoirs",
  "Euphoria Script",
  "Goblin One",
  "Major Mono Display",
  "Antonio",
  "Caladea",
  "Share Tech",
  "Iceland",
  "Unkempt",
  "Katibeh",
  "Tienne",
  "Salsa",
  "Encode Sans Semi Expanded",
  "Nova Mono",
  "Vampiro One",
  "McLaren",
  "Timmana",
  "Vollkorn SC",
  "Bellota Text",
  "Cormorant Upright",
  "RocknRoll One",
  "Codystar",
  "Baloo Chettan 2",
  "Ledger",
  "Walter Turncoat",
  "Baloo Thambi 2",
  "Arya",
  "ZCOOL QingKe HuangYou",
  "Mukta Mahee",
  "Mako",
  "Inknut Antiqua",
  "Short Stack",
  "Poller One",
  "Ranchers",
  "Montserrat Subrayada",
  "Calistoga",
  "Yusei Magic",
  "Wire One",
  "Nova Round",
  "Ruslan Display",
  "Red Rose",
  "Cherry Cream Soda",
  "Delius Swash Caps",
  "Strait",
  "Italiana",
  "Flamenco",
  "Ranga",
  "Encode Sans Expanded",
  "IM Fell English SC",
  "Mina",
  "Peralta",
  "Loved by the King",
  "Newsreader",
  "Tillana",
  "Carrois Gothic SC",
  "Trade Winds",
  "Geo",
  "Ma Shan Zheng",
  "Life Savers",
  "Crafty Girls",
  "Odibee Sans",
  "Scope One",
  "Bilbo Swash Caps",
  "Nokora",
  "Artifika",
  "Asul",
  "Lexend",
  "Engagement",
  "Gaegu",
  "Elsie",
  "Shippori Mincho",
  "Notable",
  "Dynalight",
  "Lily Script One",
  "Metamorphous",
  "The Girl Next Door",
  "Goldman",
  "Cantora One",
  "Lexend Zetta",
  "Big Shoulders Text",
  "Prosto One",
  "Imprima",
  "Coiny",
  "Headland One",
  "Puritan",
  "Amarante",
  "Englebert",
  "Sura",
  "Reggae One",
  "Gafata",
  "Manuale",
  "Cherry Swash",
  "Delius Unicase",
  "Otomanopee One",
  "Tauri",
  "Voces",
  "Encode Sans SC",
  "Bilbo",
  "Stalemate",
  "Medula One",
  "Fjord One",
  "Overlock SC",
  "Nova Square",
  "Asar",
  "Vibur",
  "UnifrakturCook",
  "Germania One",
  "Just Me Again Down Here",
  "Cormorant Unicase",
  "Slackey",
  "Sarina",
  "Fontdiner Swanky",
  "Milonga",
  "Henny Penny",
  "ZCOOL KuaiLe",
  "Syne",
  "Kodchasan",
  "Lovers Quarrel",
  "Port Lligat Slab",
  "Eater",
  "Text Me One",
  "Fresca",
  "Uchen",
  "Shanti",
  "Farro",
  "League Script",
  "Ramaraja",
  "New Rocker",
  "Habibi",
  "Simonetta",
  "Mogra",
  "Gotu",
  "Khmer",
  "Pavanam",
  "Libre Caslon Display",
  "Libre Barcode 39 Text",
  "Gamja Flower",
  "Charmonman",
  "Zen Loop",
  "Paprika",
  "Bellota",
  "Saira Stencil One",
  "Kranky",
  "Kite One",
  "Dekko",
  "Song Myung",
  "Ribeye",
  "Chau Philomene One",
  "IM Fell French Canon",
  "Baloo Paaji 2",
  "Kufam",
  "Julee",
  "Baloo Bhaina 2",
  "Sancreek",
  "Spicy Rice",
  "Qahiri",
  "IM Fell DW Pica SC",
  "Prociono",
  "Rationale",
  "Yeon Sung",
  "Kumar One",
  "Modak",
  "Fraunces",
  "Crushed",
  "Girassol",
  "Port Lligat Sans",
  "Cute Font",
  "Ibarra Real Nova",
  "Rosarivo",
  "Stoke",
  "IM Fell French Canon SC",
  "Inria Serif",
  "Moul",
  "Kotta One",
  "Petrona",
  "B612",
  "Galdeano",
  "Chicle",
  "Quintessential",
  "Zilla Slab Highlight",
  "Donegal One",
  "Macondo Swash Caps",
  "Meera Inimai",
  "Sonsie One",
  "Bubbler One",
  "Kiwi Maru",
  "Uncial Antiqua",
  "Chango",
  "Mystery Quest",
  "Pirata One",
  "Fahkwang",
  "Kulim Park",
  "Farsan",
  "Baloo Bhai 2",
  "Chela One",
  "East Sea Dokdo",
  "Londrina Outline",
  "Ruluko",
  "Angkor",
  "Averia Gruesa Libre",
  "Croissant One",
  "Sulphur Point",
  "Wellfleet",
  "Sumana",
  "Dorsa",
  "Fenix",
  "Stylish",
  "IM Fell Great Primer",
  "Bona Nova",
  "Libre Barcode 39 Extended Text",
  "STIX Two Math",
  "Nosifer",
  "Tomorrow",
  "Solway",
  "Koulen",
  "Cagliostro",
  "Redressed",
  "Sansita Swashed",
  "Akronim",
  "Sree Krushnadevaraya",
  "Junge",
  "Dela Gothic One",
  "Buda",
  "Tenali Ramakrishna",
  "Rowdies",
  "Lexend Exa",
  "Libre Barcode 128",
  "Piazzolla",
  "Offside",
  "Swanky and Moo Moo",
  "Metal",
  "Jomolhari",
  "Tulpen One",
  "Shippori Mincho B1",
  "Stint Ultra Expanded",
  "Condiment",
  "Hachi Maru Pop",
  "Lakki Reddy",
  "Nova Flat",
  "Chilanka",
  "Kdam Thmor",
  "Margarine",
  "Rum Raisin",
  "Barrio",
  "Trykker",
  "Potta One",
  "Chathura",
  "Kavivanar",
  "Train One",
  "Inika",
  "Eagle Lake",
  "Srisakdi",
  "Ruthie",
  "Sahitya",
  "Miniver",
  "Joti One",
  "Linden Hill",
  "Bayon",
  "Gorditas",
  "Modern Antiqua",
  "Autour One",
  "Sirin Stencil",
  "Devonshire",
  "Meie Script",
  "DotGothic16",
  "Maiden Orange",
  "Elsie Swash Caps",
  "Jolly Lodger",
  "Piedra",
  "Iceberg",
  "Syne Mono",
  "Londrina Shadow",
  "Kavoon",
  "Griffy",
  "Marko One",
  "Spirax",
  "Felipa",
  "Hanalei Fill",
  "Arbutus",
  "Festive",
  "Ribeye Marrow",
  "Mrs Sheppards",
  "Atomic Age",
  "Long Cang",
  "Diplomata SC",
  "Molle",
  "Monofett",
  "Caesar Dressing",
  "Asset",
  "Ravi Prakash",
  "Content",
  "Kantumruy",
  "MuseoModerno",
  "Diplomata",
  "Romanesco",
  "Lancelot",
  "Metal Mania",
  "Stick",
  "Zen Dots",
  "Rhodium Libre",
  "Ewert",
  "Flavors",
  "Bigshot One",
  "Siemreap",
  "Peddana",
  "Yomogi",
  "Nova Slim",
  "Bahiana",
  "Varta",
  "Smythe",
  "Beth Ellen",
  "Lexend Mega",
  "Snippet",
  "Londrina Sketch",
  "Poor Story",
  "Keania One",
  "Almendra SC",
  "Stalinist One",
  "Glass Antiqua",
  "Revalia",
  "Jacques Francois Shadow",
  "Gayathri",
  "Jim Nightshade",
  "Bigelow Rules",
  "Akaya Kanadaka",
  "Gupter",
  "Barriecito",
  "Risque",
  "MedievalSharp",
  "Odor Mean Chey",
  "Zen Tokyo Zoo",
  "Libre Barcode 128 Text",
  "Libre Barcode 39 Extended",
  "Mr Bedfort",
  "Sedgwick Ave Display",
  "Fascinate Inline",
  "IM Fell Great Primer SC",
  "Princess Sofia",
  "Kirang Haerang",
  "Dr Sugiyama",
  "Andika New Basic",
  "Irish Grover",
  "Freehand",
  "Bokor",
  "Oldenburg",
  "GFS Neohellenic",
  "Taprom",
  "Plaster",
  "Underdog",
  "Kumar One Outline",
  "Tourney",
  "Unlock",
  "Grenze",
  "Almendra Display",
  "Emblema One",
  "Galindo",
  "Seymour One",
  "Miss Fajardose",
  "Macondo",
  "Lexend Giga",
  "Big Shoulders Stencil Text",
  "Jacques Francois",
  "Dangrek",
  "Texturina",
  "Snowburst One",
  "Fuggles",
  "Liu Jian Mao Cao",
  "Purple Purse",
  "Inria Sans",
  "Benne",
  "IM Fell Double Pica SC",
  "Butterfly Kids",
  "Orelega One",
  "Suwannaphum",
  "Viaoda Libre",
  "Brygada 1918",
  "Federant",
  "Smokum",
  "Erica One",
  "Zhi Mang Xing",
  "Preahvihear",
  "Trochut",
  "Supermercado One",
  "Chenla",
  "Nova Script",
  "New Tegomin",
  "Sunshiney",
  "Astloch",
  "Bungee Outline",
  "Combo",
  "Hanalei",
  "Gidugu",
  "Passero One",
  "Akaya Telivigala",
  "Bonbon",
  "Nova Oval",
  "Nova Cut",
  "Black And White Picture",
  "Bungee Hairline",
  "Fascinate",
  "Ruge Boogie",
  "Sofadi One",
  "Butcherman",
  "Miltonian Tattoo",
  "Sevillana",
  "Bahianita",
  "Big Shoulders Stencil Display",
  "Miltonian",
  "Lacquer",
  "Vibes",
  "Aubrey",
  "Lexend Tera",
  "Nerko One",
  "Geostar Fill",
  "Fasthand",
  "Moulpali",
  "Suravaram",
  "Single Day",
  "Big Shoulders Inline Text",
  "Fruktur",
  "Imbue",
  "Langar",
  "BioRhyme Expanded",
  "Ballet",
  "Dhurjati",
  "Lexend Peta",
  "Xanh Mono",
  "Kenia",
  "Trispace",
  "Karantina",
  "Warnes",
  "Truculenta",
  "Geostar",
  "Oi",
  "Big Shoulders Inline Display",
  "Syne Tactile",
  "Libre Barcode EAN13 Text",
];

export const AVAILABLE_GOOGLE_FONTS_OPTIONS = AVAILABLE_GOOGLE_FONTS.map(
  (family) => ({
    label: family,
    value: family,
  })
);
